import 'package:equatable/equatable.dart';

// --- Direction Model ---
class Direction extends Equatable {
  final String title;
  final List<String> steps;

  const Direction({required this.title, required this.steps});

  factory Direction.fromJson(Map<String, dynamic> json) {
    return Direction(
      title: json['title'] ?? '',
      steps: List<String>.from(json['steps'] ?? []),
    );
  }

  Map<String, dynamic> toJson() => {'title': title, 'steps': steps};

  @override
  List<Object?> get props => [title, steps];
}

class Recipe extends Equatable {
  final String? id; // Nullable for new recipes not yet in DB
  final String title;
  final String? pictureUrl;
  final String cookTime;
  final int servings;
  final String category;
  final List<String> tags;
  final List<String> ingredients;
  final List<Direction> directions;
  final DateTime? createdAt;

  const Recipe({
    this.id,
    required this.title,
    this.pictureUrl,
    required this.cookTime,
    required this.servings,
    required this.category,
    required this.tags,
    required this.ingredients,
    required this.directions,
    this.createdAt,
  });

  // CopyWith for editing state
  Recipe copyWith({
    String? id,
    String? title,
    String? pictureUrl,
    String? cookTime,
    int? servings,
    String? category,
    List<String>? tags,
    List<String>? ingredients,
    List<Direction>? directions,
    DateTime? createdAt,
  }) {
    return Recipe(
      id: id ?? this.id,
      title: title ?? this.title,
      pictureUrl: pictureUrl ?? this.pictureUrl,
      cookTime: cookTime ?? this.cookTime,
      servings: servings ?? this.servings,
      category: category ?? this.category,
      tags: tags ?? this.tags,
      ingredients: ingredients ?? this.ingredients,
      directions: directions ?? this.directions,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  // --- Serialization for Supabase (JSONB for lists) ---
  factory Recipe.fromJson(Map<String, dynamic> json) {
    return Recipe(
      id: json['id'] as String?,
      title: json['title'] ?? '',
      pictureUrl: json['image_url'], // Mapping snake_case from DB
      cookTime: json['cook_time'] ?? '',
      servings: json['servings'] ?? 1,
      category: json['category'] ?? 'Other',
      tags: List<String>.from(json['tags'] ?? []),
      ingredients: List<String>.from(json['ingredients'] ?? []),
      directions:
          (json['directions'] as List<dynamic>?)
              ?.map((e) => Direction.fromJson(e))
              .toList() ??
          [],
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'])
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // Usually generated by DB
      'title': title,
      'image_url': pictureUrl,
      'cook_time': cookTime,
      'servings': servings,
      'category': category,
      'tags': tags,
      'ingredients': ingredients,
      'directions': directions.map((e) => e.toJson()).toList(),
      // 'created_at': created_at // Generated by DB
    };
  }

  @override
  List<Object?> get props => [
    id,
    title,
    pictureUrl,
    cookTime,
    servings,
    category,
    tags,
    ingredients,
    directions,
  ];
}
